#!/bin/bash

./log_aborts_best_case 44 00
pipenv run python ./log_to_py.py ./results/best-mldsa44-m69-s00.log ./results
pipenv run python ./gen_mldsa_inputs.py ./results/mldsa44-m69-*.py ALL --write=./results