#!/bin/bash

set -ex

NCASES=${1-5}

DSTDIR=./results-best-tv44

rm -rf $DSTDIR
mkdir -p $DSTDIR
PSET=44
HDRBG_SEED=00
MSG_SIZE=69
LOG_PREFIX=best
DSTLOG=$DSTDIR/${LOG_PREFIX}-${PSET}-m${MSG_SIZE}-s${HDRBG_SEED}.log
FLAGS="mldsa$PSET --msg-size=$MSG_SIZE --hdrbg-seed=$HDRBG_SEED --stop-at=$NCASES --exact-repetitions --min-repetitions=1 --exact-sib-bytes --hbp-index=50"
time ./mldsa-tv-gen $FLAGS ${@: 2} > $DSTLOG
pipenv run python ./log_to_py.py $DSTLOG $DSTDIR
pipenv run python ./gen_mldsa_inputs.py $DSTDIR/mldsa${PSET}-m${MSG_SIZE}-*.py ALL --write=$DSTDIR